/* 
 * Live Validation Service Client
 *
 * Client that can be used to access Live Validation Service.
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;
using IO.Swagger.Model;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ValidateApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class ValidateApiTests
    {
        private ValidateApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new ValidateApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ValidateApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' ValidateApi
            //Assert.IsInstanceOfType(typeof(ValidateApi), instance, "instance is a ValidateApi");
        }

        
        /// <summary>
        /// Test ToolsLiveValidationValidate
        /// </summary>
        [Test]
        public void ToolsLiveValidationValidateTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //LiveValidationParameter liveValidationParameter = null;
            //var response = instance.ToolsLiveValidationValidate(liveValidationParameter);
            //Assert.IsInstanceOf<LiveValidationResponse> (response, "response is LiveValidationResponse");
        }
        
    }

}
