/* 
 * Live Validation Service Client
 *
 * Client that can be used to access Live Validation Service.
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;
using IO.Swagger.Model;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing WhitelistApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class WhitelistApiTests
    {
        private WhitelistApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new WhitelistApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of WhitelistApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' WhitelistApi
            //Assert.IsInstanceOfType(typeof(WhitelistApi), instance, "instance is a WhitelistApi");
        }

        
        /// <summary>
        /// Test ToolsLiveValidationProdWhiteList
        /// </summary>
        [Test]
        public void ToolsLiveValidationProdWhiteListTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.ToolsLiveValidationProdWhiteList();
            //Assert.IsInstanceOf<LiveValidationWhiteListResponse> (response, "response is LiveValidationWhiteListResponse");
        }
        
        /// <summary>
        /// Test ToolsLiveValidationWhiteList
        /// </summary>
        [Test]
        public void ToolsLiveValidationWhiteListTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.ToolsLiveValidationWhiteList();
            //Assert.IsInstanceOf<LiveValidationWhiteListResponse> (response, "response is LiveValidationWhiteListResponse");
        }
        
    }

}
