/* 
 * Live Validation Service Client
 *
 * Client that can be used to access Live Validation Service.
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// Live Validation response
    /// </summary>
    [DataContract]
    public partial class LiveValidationResponse :  IEquatable<LiveValidationResponse>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="LiveValidationResponse" /> class.
        /// </summary>
        /// <param name="RequestValidationResult">Validation result of the live request.</param>
        /// <param name="ResponseValidationResult">Validation result of the live response.</param>
        /// <param name="Errors">List of Errors..</param>
        public LiveValidationResponse(RequestValidationResult RequestValidationResult = default(RequestValidationResult), ResponseValidationResult ResponseValidationResult = default(ResponseValidationResult), List<Object> Errors = default(List<Object>))
        {
            this.RequestValidationResult = RequestValidationResult;
            this.ResponseValidationResult = ResponseValidationResult;
            this.Errors = Errors;
        }
        
        /// <summary>
        /// Validation result of the live request
        /// </summary>
        /// <value>Validation result of the live request</value>
        [DataMember(Name="requestValidationResult", EmitDefaultValue=false)]
        public RequestValidationResult RequestValidationResult { get; set; }

        /// <summary>
        /// Validation result of the live response
        /// </summary>
        /// <value>Validation result of the live response</value>
        [DataMember(Name="responseValidationResult", EmitDefaultValue=false)]
        public ResponseValidationResult ResponseValidationResult { get; set; }

        /// <summary>
        /// List of Errors.
        /// </summary>
        /// <value>List of Errors.</value>
        [DataMember(Name="errors", EmitDefaultValue=false)]
        public List<Object> Errors { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class LiveValidationResponse {\n");
            sb.Append("  RequestValidationResult: ").Append(RequestValidationResult).Append("\n");
            sb.Append("  ResponseValidationResult: ").Append(ResponseValidationResult).Append("\n");
            sb.Append("  Errors: ").Append(Errors).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as LiveValidationResponse);
        }

        /// <summary>
        /// Returns true if LiveValidationResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of LiveValidationResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(LiveValidationResponse input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.RequestValidationResult == input.RequestValidationResult ||
                    (this.RequestValidationResult != null &&
                    this.RequestValidationResult.Equals(input.RequestValidationResult))
                ) && 
                (
                    this.ResponseValidationResult == input.ResponseValidationResult ||
                    (this.ResponseValidationResult != null &&
                    this.ResponseValidationResult.Equals(input.ResponseValidationResult))
                ) && 
                (
                    this.Errors == input.Errors ||
                    this.Errors != null &&
                    this.Errors.SequenceEqual(input.Errors)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.RequestValidationResult != null)
                    hashCode = hashCode * 59 + this.RequestValidationResult.GetHashCode();
                if (this.ResponseValidationResult != null)
                    hashCode = hashCode * 59 + this.ResponseValidationResult.GetHashCode();
                if (this.Errors != null)
                    hashCode = hashCode * 59 + this.Errors.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
