/* 
 * Live Validation Service Client
 *
 * Client that can be used to access Live Validation Service.
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing LiveValidationWhiteListResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class LiveValidationWhiteListResponseTests
    {
        // TODO uncomment below to declare an instance variable for LiveValidationWhiteListResponse
        //private LiveValidationWhiteListResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of LiveValidationWhiteListResponse
            //instance = new LiveValidationWhiteListResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of LiveValidationWhiteListResponse
        /// </summary>
        [Test]
        public void LiveValidationWhiteListResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" LiveValidationWhiteListResponse
            //Assert.IsInstanceOfType<LiveValidationWhiteListResponse> (instance, "variable 'instance' is a LiveValidationWhiteListResponse");
        }


        /// <summary>
        /// Test the property 'SafeProperties'
        /// </summary>
        [Test]
        public void SafePropertiesTest()
        {
            // TODO unit test for the property 'SafeProperties'
        }

    }

}
