/* 
 * Live Validation Service Client
 *
 * Client that can be used to access Live Validation Service.
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing LiveResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class LiveResponseTests
    {
        // TODO uncomment below to declare an instance variable for LiveResponse
        //private LiveResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of LiveResponse
            //instance = new LiveResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of LiveResponse
        /// </summary>
        [Test]
        public void LiveResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" LiveResponse
            //Assert.IsInstanceOfType<LiveResponse> (instance, "variable 'instance' is a LiveResponse");
        }


        /// <summary>
        /// Test the property 'StatusCode'
        /// </summary>
        [Test]
        public void StatusCodeTest()
        {
            // TODO unit test for the property 'StatusCode'
        }
        /// <summary>
        /// Test the property 'Headers'
        /// </summary>
        [Test]
        public void HeadersTest()
        {
            // TODO unit test for the property 'Headers'
        }
        /// <summary>
        /// Test the property 'Body'
        /// </summary>
        [Test]
        public void BodyTest()
        {
            // TODO unit test for the property 'Body'
        }

    }

}
