/* 
 * Live Validation Service Client
 *
 * Client that can be used to access Live Validation Service.
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing LiveValidationResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class LiveValidationResponseTests
    {
        // TODO uncomment below to declare an instance variable for LiveValidationResponse
        //private LiveValidationResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of LiveValidationResponse
            //instance = new LiveValidationResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of LiveValidationResponse
        /// </summary>
        [Test]
        public void LiveValidationResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" LiveValidationResponse
            //Assert.IsInstanceOfType<LiveValidationResponse> (instance, "variable 'instance' is a LiveValidationResponse");
        }


        /// <summary>
        /// Test the property 'RequestValidationResult'
        /// </summary>
        [Test]
        public void RequestValidationResultTest()
        {
            // TODO unit test for the property 'RequestValidationResult'
        }
        /// <summary>
        /// Test the property 'ResponseValidationResult'
        /// </summary>
        [Test]
        public void ResponseValidationResultTest()
        {
            // TODO unit test for the property 'ResponseValidationResult'
        }
        /// <summary>
        /// Test the property 'Errors'
        /// </summary>
        [Test]
        public void ErrorsTest()
        {
            // TODO unit test for the property 'Errors'
        }

    }

}
