/* 
 * Live Validation Service Client
 *
 * Client that can be used to access Live Validation Service.
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ResponseValidationResult
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ResponseValidationResultTests
    {
        // TODO uncomment below to declare an instance variable for ResponseValidationResult
        //private ResponseValidationResult instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ResponseValidationResult
            //instance = new ResponseValidationResult();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ResponseValidationResult
        /// </summary>
        [Test]
        public void ResponseValidationResultInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ResponseValidationResult
            //Assert.IsInstanceOfType<ResponseValidationResult> (instance, "variable 'instance' is a ResponseValidationResult");
        }


        /// <summary>
        /// Test the property 'SuccessfulResponse'
        /// </summary>
        [Test]
        public void SuccessfulResponseTest()
        {
            // TODO unit test for the property 'SuccessfulResponse'
        }
        /// <summary>
        /// Test the property 'Errors'
        /// </summary>
        [Test]
        public void ErrorsTest()
        {
            // TODO unit test for the property 'Errors'
        }
        /// <summary>
        /// Test the property 'OperationInfo'
        /// </summary>
        [Test]
        public void OperationInfoTest()
        {
            // TODO unit test for the property 'OperationInfo'
        }

    }

}
