/* 
 * Live Validation Service Client
 *
 * Client that can be used to access Live Validation Service.
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp;
using IO.Swagger.Client;
using IO.Swagger.Model;

namespace IO.Swagger.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ILiveValidationApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Process Prod environment ARM calls.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="liveValidationParameter">Live Validation Parameter</param>
        /// <returns>LiveValidationResponse</returns>
        LiveValidationResponse ToolsLiveValidationProdValidate (LiveValidationParameter liveValidationParameter);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Process Prod environment ARM calls.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="liveValidationParameter">Live Validation Parameter</param>
        /// <returns>ApiResponse of LiveValidationResponse</returns>
        ApiResponse<LiveValidationResponse> ToolsLiveValidationProdValidateWithHttpInfo (LiveValidationParameter liveValidationParameter);
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Get list of safe properties is prod environments.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>LiveValidationWhiteListResponse</returns>
        LiveValidationWhiteListResponse ToolsLiveValidationProdWhiteList ();

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Get list of safe properties is prod environments.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of LiveValidationWhiteListResponse</returns>
        ApiResponse<LiveValidationWhiteListResponse> ToolsLiveValidationProdWhiteListWithHttpInfo ();
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Process non-prod canary environment ARM calls.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="liveValidationParameter">Live Validation Parameter</param>
        /// <returns>LiveValidationResponse</returns>
        LiveValidationResponse ToolsLiveValidationValidate (LiveValidationParameter liveValidationParameter);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Process non-prod canary environment ARM calls.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="liveValidationParameter">Live Validation Parameter</param>
        /// <returns>ApiResponse of LiveValidationResponse</returns>
        ApiResponse<LiveValidationResponse> ToolsLiveValidationValidateWithHttpInfo (LiveValidationParameter liveValidationParameter);
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Get list of safe properties in non-prod canary environments.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>LiveValidationWhiteListResponse</returns>
        LiveValidationWhiteListResponse ToolsLiveValidationWhiteList ();

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Get list of safe properties in non-prod canary environments.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of LiveValidationWhiteListResponse</returns>
        ApiResponse<LiveValidationWhiteListResponse> ToolsLiveValidationWhiteListWithHttpInfo ();
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Process Prod environment ARM calls.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="liveValidationParameter">Live Validation Parameter</param>
        /// <returns>Task of LiveValidationResponse</returns>
        System.Threading.Tasks.Task<LiveValidationResponse> ToolsLiveValidationProdValidateAsync (LiveValidationParameter liveValidationParameter);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Process Prod environment ARM calls.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="liveValidationParameter">Live Validation Parameter</param>
        /// <returns>Task of ApiResponse (LiveValidationResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<LiveValidationResponse>> ToolsLiveValidationProdValidateAsyncWithHttpInfo (LiveValidationParameter liveValidationParameter);
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Get list of safe properties is prod environments.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of LiveValidationWhiteListResponse</returns>
        System.Threading.Tasks.Task<LiveValidationWhiteListResponse> ToolsLiveValidationProdWhiteListAsync ();

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Get list of safe properties is prod environments.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of ApiResponse (LiveValidationWhiteListResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<LiveValidationWhiteListResponse>> ToolsLiveValidationProdWhiteListAsyncWithHttpInfo ();
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Process non-prod canary environment ARM calls.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="liveValidationParameter">Live Validation Parameter</param>
        /// <returns>Task of LiveValidationResponse</returns>
        System.Threading.Tasks.Task<LiveValidationResponse> ToolsLiveValidationValidateAsync (LiveValidationParameter liveValidationParameter);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Process non-prod canary environment ARM calls.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="liveValidationParameter">Live Validation Parameter</param>
        /// <returns>Task of ApiResponse (LiveValidationResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<LiveValidationResponse>> ToolsLiveValidationValidateAsyncWithHttpInfo (LiveValidationParameter liveValidationParameter);
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Get list of safe properties in non-prod canary environments.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of LiveValidationWhiteListResponse</returns>
        System.Threading.Tasks.Task<LiveValidationWhiteListResponse> ToolsLiveValidationWhiteListAsync ();

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Get list of safe properties in non-prod canary environments.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of ApiResponse (LiveValidationWhiteListResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<LiveValidationWhiteListResponse>> ToolsLiveValidationWhiteListAsyncWithHttpInfo ();
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class LiveValidationApi : ILiveValidationApi
    {
        private IO.Swagger.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="LiveValidationApi"/> class.
        /// </summary>
        /// <returns></returns>
        public LiveValidationApi(String basePath)
        {
            this.Configuration = new Configuration { BasePath = basePath };

            ExceptionFactory = IO.Swagger.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="LiveValidationApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public LiveValidationApi(Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = IO.Swagger.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public IO.Swagger.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<String, String> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(this.Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        ///  Process Prod environment ARM calls.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="liveValidationParameter">Live Validation Parameter</param>
        /// <returns>LiveValidationResponse</returns>
        public LiveValidationResponse ToolsLiveValidationProdValidate (LiveValidationParameter liveValidationParameter)
        {
             ApiResponse<LiveValidationResponse> localVarResponse = ToolsLiveValidationProdValidateWithHttpInfo(liveValidationParameter);
             return localVarResponse.Data;
        }

        /// <summary>
        ///  Process Prod environment ARM calls.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="liveValidationParameter">Live Validation Parameter</param>
        /// <returns>ApiResponse of LiveValidationResponse</returns>
        public ApiResponse< LiveValidationResponse > ToolsLiveValidationProdValidateWithHttpInfo (LiveValidationParameter liveValidationParameter)
        {
            // verify the required parameter 'liveValidationParameter' is set
            if (liveValidationParameter == null)
                throw new ApiException(400, "Missing required parameter 'liveValidationParameter' when calling LiveValidationApi->ToolsLiveValidationProdValidate");

            var localVarPath = "/prod/validate";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (liveValidationParameter != null && liveValidationParameter.GetType() != typeof(byte[]))
            {
                localVarPostBody = Configuration.ApiClient.Serialize(liveValidationParameter); // http body (model) parameter
            }
            else
            {
                localVarPostBody = liveValidationParameter; // byte array
            }


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("ToolsLiveValidationProdValidate", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<LiveValidationResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (LiveValidationResponse) Configuration.ApiClient.Deserialize(localVarResponse, typeof(LiveValidationResponse)));
        }

        /// <summary>
        ///  Process Prod environment ARM calls.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="liveValidationParameter">Live Validation Parameter</param>
        /// <returns>Task of LiveValidationResponse</returns>
        public async System.Threading.Tasks.Task<LiveValidationResponse> ToolsLiveValidationProdValidateAsync (LiveValidationParameter liveValidationParameter)
        {
             ApiResponse<LiveValidationResponse> localVarResponse = await ToolsLiveValidationProdValidateAsyncWithHttpInfo(liveValidationParameter);
             return localVarResponse.Data;

        }

        /// <summary>
        ///  Process Prod environment ARM calls.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="liveValidationParameter">Live Validation Parameter</param>
        /// <returns>Task of ApiResponse (LiveValidationResponse)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<LiveValidationResponse>> ToolsLiveValidationProdValidateAsyncWithHttpInfo (LiveValidationParameter liveValidationParameter)
        {
            // verify the required parameter 'liveValidationParameter' is set
            if (liveValidationParameter == null)
                throw new ApiException(400, "Missing required parameter 'liveValidationParameter' when calling LiveValidationApi->ToolsLiveValidationProdValidate");

            var localVarPath = "/prod/validate";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (liveValidationParameter != null && liveValidationParameter.GetType() != typeof(byte[]))
            {
                localVarPostBody = Configuration.ApiClient.Serialize(liveValidationParameter); // http body (model) parameter
            }
            else
            {
                localVarPostBody = liveValidationParameter; // byte array
            }


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("ToolsLiveValidationProdValidate", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<LiveValidationResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (LiveValidationResponse) Configuration.ApiClient.Deserialize(localVarResponse, typeof(LiveValidationResponse)));
        }

        /// <summary>
        ///  Get list of safe properties is prod environments.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>LiveValidationWhiteListResponse</returns>
        public LiveValidationWhiteListResponse ToolsLiveValidationProdWhiteList ()
        {
             ApiResponse<LiveValidationWhiteListResponse> localVarResponse = ToolsLiveValidationProdWhiteListWithHttpInfo();
             return localVarResponse.Data;
        }

        /// <summary>
        ///  Get list of safe properties is prod environments.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of LiveValidationWhiteListResponse</returns>
        public ApiResponse< LiveValidationWhiteListResponse > ToolsLiveValidationProdWhiteListWithHttpInfo ()
        {

            var localVarPath = "/prod/whitelist";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);



            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("ToolsLiveValidationProdWhiteList", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<LiveValidationWhiteListResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (LiveValidationWhiteListResponse) Configuration.ApiClient.Deserialize(localVarResponse, typeof(LiveValidationWhiteListResponse)));
        }

        /// <summary>
        ///  Get list of safe properties is prod environments.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of LiveValidationWhiteListResponse</returns>
        public async System.Threading.Tasks.Task<LiveValidationWhiteListResponse> ToolsLiveValidationProdWhiteListAsync ()
        {
             ApiResponse<LiveValidationWhiteListResponse> localVarResponse = await ToolsLiveValidationProdWhiteListAsyncWithHttpInfo();
             return localVarResponse.Data;

        }

        /// <summary>
        ///  Get list of safe properties is prod environments.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of ApiResponse (LiveValidationWhiteListResponse)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<LiveValidationWhiteListResponse>> ToolsLiveValidationProdWhiteListAsyncWithHttpInfo ()
        {

            var localVarPath = "/prod/whitelist";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);



            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("ToolsLiveValidationProdWhiteList", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<LiveValidationWhiteListResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (LiveValidationWhiteListResponse) Configuration.ApiClient.Deserialize(localVarResponse, typeof(LiveValidationWhiteListResponse)));
        }

        /// <summary>
        ///  Process non-prod canary environment ARM calls.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="liveValidationParameter">Live Validation Parameter</param>
        /// <returns>LiveValidationResponse</returns>
        public LiveValidationResponse ToolsLiveValidationValidate (LiveValidationParameter liveValidationParameter)
        {
             ApiResponse<LiveValidationResponse> localVarResponse = ToolsLiveValidationValidateWithHttpInfo(liveValidationParameter);
             return localVarResponse.Data;
        }

        /// <summary>
        ///  Process non-prod canary environment ARM calls.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="liveValidationParameter">Live Validation Parameter</param>
        /// <returns>ApiResponse of LiveValidationResponse</returns>
        public ApiResponse< LiveValidationResponse > ToolsLiveValidationValidateWithHttpInfo (LiveValidationParameter liveValidationParameter)
        {
            // verify the required parameter 'liveValidationParameter' is set
            if (liveValidationParameter == null)
                throw new ApiException(400, "Missing required parameter 'liveValidationParameter' when calling LiveValidationApi->ToolsLiveValidationValidate");

            var localVarPath = "/validate";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (liveValidationParameter != null && liveValidationParameter.GetType() != typeof(byte[]))
            {
                localVarPostBody = Configuration.ApiClient.Serialize(liveValidationParameter); // http body (model) parameter
            }
            else
            {
                localVarPostBody = liveValidationParameter; // byte array
            }


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("ToolsLiveValidationValidate", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<LiveValidationResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (LiveValidationResponse) Configuration.ApiClient.Deserialize(localVarResponse, typeof(LiveValidationResponse)));
        }

        /// <summary>
        ///  Process non-prod canary environment ARM calls.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="liveValidationParameter">Live Validation Parameter</param>
        /// <returns>Task of LiveValidationResponse</returns>
        public async System.Threading.Tasks.Task<LiveValidationResponse> ToolsLiveValidationValidateAsync (LiveValidationParameter liveValidationParameter)
        {
             ApiResponse<LiveValidationResponse> localVarResponse = await ToolsLiveValidationValidateAsyncWithHttpInfo(liveValidationParameter);
             return localVarResponse.Data;

        }

        /// <summary>
        ///  Process non-prod canary environment ARM calls.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="liveValidationParameter">Live Validation Parameter</param>
        /// <returns>Task of ApiResponse (LiveValidationResponse)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<LiveValidationResponse>> ToolsLiveValidationValidateAsyncWithHttpInfo (LiveValidationParameter liveValidationParameter)
        {
            // verify the required parameter 'liveValidationParameter' is set
            if (liveValidationParameter == null)
                throw new ApiException(400, "Missing required parameter 'liveValidationParameter' when calling LiveValidationApi->ToolsLiveValidationValidate");

            var localVarPath = "/validate";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (liveValidationParameter != null && liveValidationParameter.GetType() != typeof(byte[]))
            {
                localVarPostBody = Configuration.ApiClient.Serialize(liveValidationParameter); // http body (model) parameter
            }
            else
            {
                localVarPostBody = liveValidationParameter; // byte array
            }


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("ToolsLiveValidationValidate", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<LiveValidationResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (LiveValidationResponse) Configuration.ApiClient.Deserialize(localVarResponse, typeof(LiveValidationResponse)));
        }

        /// <summary>
        ///  Get list of safe properties in non-prod canary environments.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>LiveValidationWhiteListResponse</returns>
        public LiveValidationWhiteListResponse ToolsLiveValidationWhiteList ()
        {
             ApiResponse<LiveValidationWhiteListResponse> localVarResponse = ToolsLiveValidationWhiteListWithHttpInfo();
             return localVarResponse.Data;
        }

        /// <summary>
        ///  Get list of safe properties in non-prod canary environments.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of LiveValidationWhiteListResponse</returns>
        public ApiResponse< LiveValidationWhiteListResponse > ToolsLiveValidationWhiteListWithHttpInfo ()
        {

            var localVarPath = "/whitelist";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);



            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("ToolsLiveValidationWhiteList", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<LiveValidationWhiteListResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (LiveValidationWhiteListResponse) Configuration.ApiClient.Deserialize(localVarResponse, typeof(LiveValidationWhiteListResponse)));
        }

        /// <summary>
        ///  Get list of safe properties in non-prod canary environments.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of LiveValidationWhiteListResponse</returns>
        public async System.Threading.Tasks.Task<LiveValidationWhiteListResponse> ToolsLiveValidationWhiteListAsync ()
        {
             ApiResponse<LiveValidationWhiteListResponse> localVarResponse = await ToolsLiveValidationWhiteListAsyncWithHttpInfo();
             return localVarResponse.Data;

        }

        /// <summary>
        ///  Get list of safe properties in non-prod canary environments.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of ApiResponse (LiveValidationWhiteListResponse)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<LiveValidationWhiteListResponse>> ToolsLiveValidationWhiteListAsyncWithHttpInfo ()
        {

            var localVarPath = "/whitelist";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);



            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("ToolsLiveValidationWhiteList", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<LiveValidationWhiteListResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (LiveValidationWhiteListResponse) Configuration.ApiClient.Deserialize(localVarResponse, typeof(LiveValidationWhiteListResponse)));
        }

    }
}
